### ISSUE TITLE
agar ak number per do martaba insurance hote ha  to error ata ha esa fix karo error nhi alert ana chaiya ak number per do martaba insurance nhi ho sakte

### ISSUE THREAD

**Issue by naveed21-m** [usamach559/Tammin#9]
<img width="960" alt="Screenshot 2024-11-23 160510" src="https://github.com/user-attachments/assets/61ad9ed0-7d15-4852-9c4a-fee5892ee6ed">

**Comment by usamach559** [comment]
insurance me ata h yeh
